{
  "language": "java",
  "jdk": "oraclejdk8",
  "script": [
    "./mvnw test"
  ],
  "after_success": [
    "./mvnw clean cobertura:cobertura coveralls:report"
  ],
  "group": "stable",
  "dist": "precise"
}